// Generated by CoffeeScript 1.8.0
(function() {
  controllers.controller('createCodeReviewCtrl', function($scope, $rootScope, $modalInstance, $modal, ReviewRequest) {
    var setAcceptStatus;
    $scope.codeReview = {};
    $scope.reviewRequests = [];
    $scope.values = $rootScope.values;
    $scope.codeReview.value = $scope.values[0];
    setAcceptStatus = function() {
      return $scope.accepted = ReviewRequest.accepted;
    };
    setAcceptStatus();
    $scope.createReviewRequest = function() {
      return ReviewRequest.create($scope.codeReview).then(function(newReviewRequest) {
        setAcceptStatus();
        $rootScope.$broadcast('new-request-created');
        return $modalInstance.dismiss('cancel');
      });
    };
    return $scope.cancel = function() {
      return $modalInstance.dismiss('cancel');
    };
  });

}).call(this);
